name = "riftgate"
main = "./build/worker.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
no_bundle = true
find_additional_modules = true

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[build]
command = "npm run build"

[[durable_objects.bindings]]
name = "SIGNALING_ROOM"
class_name = "SignalingRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SignalingRoom"]
